export const ON_CHANGE_STEP_REGISTER = "ON_CHANGE_STEP_REGISTER";

export const ENDING_STEP_REGISTER  = "ENDING_STEP_REGISTER";

export const ADD_NEW_USER_EMAIL_PASSWORD = "ADD_NEW_USER_EMAIL_PASSWORD";

export const ADD_NEW_DATA_USER = "ADD_NEW_DATA_USER";